services:
  weston:
    network_mode: host
    cap_add:
      - CAP_SYS_TTY_CONFIG
    volumes:
      - '/dev:/dev'
      - '/tmp:/tmp'
      - '/run/udev/:/run/udev/'
    device_cgroup_rules:
      - 'c 4:* rmw'
      - 'c 13:* rmw'
      - 'c 226:* rmw'
    image: 'torizon/weston-am62:4'
    command: '--developer'

  spinning-cube:
    depends_on:
      - weston
    device_cgroup_rules:
      - 'c 226:* rmw'
    image: 'ghcr.io/leonheldattoradex/ti-toradex-spinny:v0.0.2'
    volumes:
      - '/tmp:/tmp'
      - '/dev/dri:/dev/dri'
    command: ./SpinningCube
